package tests

import (
	"flag"
	"fmt"
	"os"
	"testing"

	"github.com/rancher/charts/testing/builder"
	"github.com/rancher/charts/tests/setup"
	"github.com/sirupsen/logrus"
	"k8s.io/kubectl/pkg/scheme"
)

// NOTE: Do not modify. This file is automatically generated by ./scripts/sync-tests

var (
	suite = builder.NewTestSuite(packageName)

	strict         = flag.Bool("strict", true, "fail if any object cannot be decoded")
	chartDirectory = flag.String("chart", fmt.Sprintf("packages/%s/charts", packageName), "dir pointing to Helm chart")
)

func TestMain(m *testing.M) {
	if err := setup.Setup(); err != nil {
		logrus.Error(err)
		os.Exit(1)
	}

	s := scheme.Scheme
	addPackageSchemes(s)
	suite.SetCustomScheme(s)

	if err := setup.ParseValuesForChart(suite, *chartDirectory, *strict); err != nil {
		logrus.Error(err)
		os.Exit(1)
	}

	code := m.Run()
	os.Exit(code)
}
