#!/bin/bash
set -e

cd $(dirname $0)

cd ..

if [ -z ${PACKAGE} ]; then
    echo "usage: PACKAGE={packageName} make initialize-tests"
    exit 1
fi

if ! [ -d packages/${PACKAGE} ]; then
    echo "Package packages/${PACKAGE} does not exist."
    exit 1
fi

if [[ -d packages/${PACKAGE}/tests && -n "$(ls -A packages/${PACKAGE}/tests)" ]]; then
    echo "Test directory packages/${PACKAGE}/tests is already initialized."
    exit 0
fi

mkdir -p packages/${PACKAGE}/tests

cp -R tests/template/tests/* packages/${PACKAGE}/tests

rm packages/${PACKAGE}/tests/package.go

cat <<EOF >  packages/${PACKAGE}/tests/package.go
package tests

const (
	packageName = "${PACKAGE}"
)
EOF

echo "Initialized packages/${PACKAGE}/tests based on template."

