#!/bin/bash
set -e

cd $(dirname $0)

cd ..

TESTS=$(find packages -type f -regex "packages/[^/]*/tests/.*\.go" \
    | rev | cut -d'/' -f2- | rev \
    | awk '{ print "    _ \"github.com/rancher/charts/"$0"\""}' \
    | sort)

if [ -z "${TESTS}" ]; then
    echo "package register" > testing/register/all.go
    go mod tidy
    exit 0
fi

cat <<EOF > testing/register/all.go
package register

import (
${TESTS}
)
EOF
go mod tidy
